# Generated by Django 6.0.1 on 2026-01-18 23:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAnalise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo_pdf', models.FileField(upload_to='processos_pdfs/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
                ('resumo_ia', models.TextField(blank=True, null=True, verbose_name='Resumo Geral')),
                ('pontos_fortes', models.TextField(blank=True, null=True)),
                ('pontos_fracos', models.TextField(blank=True, null=True)),
                ('sugestao_estrategica', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
    ]
