# Generated by Django 5.2.7 on 2026-01-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoanalise',
            name='timeline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
